name       : ddclient
version    : 3.9.1
release    : 8
source     :
    - https://github.com/ddclient/ddclient/archive/v3.9.1.tar.gz : e4969e15cc491fc52bdcd649d4c2b0e4b1bf0c9f9dba23471c634871acc52470
homepage   : https://ddclient.net/
license    : GPL-2.0-or-later
component  : network.client
summary    : ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services
description: |
    ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services.
rundeps    :
    - perl-data-validate-ip
    - perl-io-socket-ssl
    - perl-netaddr-ip
install    : |
    install -Dm00755 ddclient $installdir/usr/sbin/ddclient
    install -Dm00600 sample-etc_ddclient.conf $installdir/etc/ddclient/ddclient.conf
    install -Dm00644 $pkgfiles/ddclient.service $installdir/usr/lib64/systemd/system/ddclient.service
    install -Dm00644 $pkgfiles/ddclient.tmpfiles $installdir/usr/lib64/tmpfiles.d/ddclient.conf
