name       : ddclient
version    : 3.8.3
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/ddclient/ddclient/ddclient-3.8.3/ddclient-3.8.3.tar.gz : debd5fec69eeb65e2331b86f5280f382416d97ed103839a65c201eef8e6d1fc9
license    : GPL-2.0
component  : network.client
summary    : ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services
description: |
    ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services
install    : |
    install -D -m 00755 ddclient $installdir/usr/sbin/ddclient
    install -D -m 00600 sample-etc_ddclient.conf $installdir/etc/ddclient/ddclient.conf
    install -D -m 00644 $pkgfiles/ddclient.service $installdir/usr/lib64/systemd/system/ddclient.service