name       : ddclient
version    : 3.9.0
release    : 4
source     :
    - https://github.com/ddclient/ddclient/archive/v3.9.0.tar.gz : 9c4ae902742e8a37790d3cc8fad4e5b0f38154c76bba3643f4423d8f96829e3b
license    : GPL-2.0
component  : network.client
summary    : ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services
rundeps    :
    - perl-io-socket-ssl
description: |
    ddclient is a Perl client used to update dynamic DNS entries for accounts on many dynamic DNS services
install    : |
    install -D -m 00755 ddclient $installdir/usr/sbin/ddclient
    install -D -m 00600 sample-etc_ddclient.conf $installdir/etc/ddclient/ddclient.conf
    install -D -m 00644 $pkgfiles/ddclient.service $installdir/usr/lib64/systemd/system/ddclient.service
    install -D -m 00644 $pkgfiles/ddclient.tmpfiles $installdir/usr/lib64/tmpfiles.d/ddclient.conf
